<?php

namespace Database\Seeders;

use App\Models\DiagnosaSdki;
use App\Models\IntervensiSiki;
use App\Models\LuaranSlki;
use Illuminate\Database\Seeder;

class SdkiSlkiSikiSeeder extends Seeder
{
    public function run(): void
    {
        $this->seedSdki();
        $this->seedSlki();
        $this->seedSiki();
    }

    private function seedSdki(): void
    {
        // [kode, label, kategori, subkategori] — 149 diagnosa SDKI
        $data = [
            ['D.0001', 'Bersihan Jalan Napas Tidak Efektif', 'Fisiologis', 'Respirasi'],
            ['D.0002', 'Gangguan Penyapihan Ventilator', 'Fisiologis', 'Respirasi'],
            ['D.0003', 'Gangguan Pertukaran Gas', 'Fisiologis', 'Respirasi'],
            ['D.0004', 'Gangguan Ventilasi Spontan', 'Fisiologis', 'Respirasi'],
            ['D.0005', 'Pola Napas Tidak Efektif', 'Fisiologis', 'Respirasi'],
            ['D.0006', 'Risiko Aspirasi', 'Fisiologis', 'Respirasi'],
            ['D.0007', 'Gangguan Sirkulasi Spontan', 'Fisiologis', 'Sirkulasi'],
            ['D.0008', 'Penurunan Curah Jantung', 'Fisiologis', 'Sirkulasi'],
            ['D.0009', 'Perfusi Perifer Tidak Efektif', 'Fisiologis', 'Sirkulasi'],
            ['D.0010', 'Risiko Gangguan Sirkulasi Spontan', 'Fisiologis', 'Sirkulasi'],
            ['D.0011', 'Risiko Penurunan Curah Jantung', 'Fisiologis', 'Sirkulasi'],
            ['D.0012', 'Risiko Perfusi Gastrointestinal Tidak Efektif', 'Fisiologis', 'Sirkulasi'],
            ['D.0013', 'Risiko Perfusi Miokard Tidak Efektif', 'Fisiologis', 'Sirkulasi'],
            ['D.0014', 'Risiko Perfusi Perifer Tidak Efektif', 'Fisiologis', 'Sirkulasi'],
            ['D.0015', 'Risiko Perfusi Renal Tidak Efektif', 'Fisiologis', 'Sirkulasi'],
            ['D.0016', 'Risiko Perfusi Serebral Tidak Efektif', 'Fisiologis', 'Sirkulasi'],
            ['D.0017', 'Defisit Nutrisi', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0018', 'Berat Badan Lebih', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0019', 'Defisit Volume Cairan', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0020', 'Diare', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0021', 'Disfungsi Motilitas Gastrointestinal', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0022', 'Hipervolemia', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0023', 'Hipovolemia', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0024', 'Ikterus Neonatus', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0025', 'Kesiapan Peningkatan Keseimbangan Cairan', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0026', 'Kesiapan Peningkatan Nutrisi', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0027', 'Ketidakstabilan Kadar Glukosa Darah', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0028', 'Menyusui Efektif', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0029', 'Menyusui Tidak Efektif', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0030', 'Obesitas', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0031', 'Risiko Berat Badan Lebih', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0032', 'Risiko Defisit Nutrisi', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0033', 'Risiko Disfungsi Motilitas Gastrointestinal', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0034', 'Risiko Hipovolemia', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0035', 'Risiko Ikterus Neonatus', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0036', 'Risiko Ketidakseimbangan Cairan', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0037', 'Risiko Ketidakseimbangan Elektrolit', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0038', 'Risiko Ketidakstabilan Kadar Glukosa Darah', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0039', 'Risiko Syok', 'Fisiologis', 'Nutrisi & Cairan'],
            ['D.0040', 'Gangguan Eliminasi Urin', 'Fisiologis', 'Eliminasi'],
            ['D.0041', 'Inkontinensia Urin Berlanjut', 'Fisiologis', 'Eliminasi'],
            ['D.0042', 'Inkontinensia Urin Berlebih', 'Fisiologis', 'Eliminasi'],
            ['D.0043', 'Inkontinensia Urin Fungsional', 'Fisiologis', 'Eliminasi'],
            ['D.0044', 'Inkontinensia Urin Refleks', 'Fisiologis', 'Eliminasi'],
            ['D.0045', 'Inkontinensia Urin Stress', 'Fisiologis', 'Eliminasi'],
            ['D.0046', 'Inkontinensia Urin Urgensi', 'Fisiologis', 'Eliminasi'],
            ['D.0047', 'Kesiapan Peningkatan Eliminasi Urin', 'Fisiologis', 'Eliminasi'],
            ['D.0048', 'Konstipasi', 'Fisiologis', 'Eliminasi'],
            ['D.0049', 'Retensi Urin', 'Fisiologis', 'Eliminasi'],
            ['D.0050', 'Risiko Konstipasi', 'Fisiologis', 'Eliminasi'],
            ['D.0051', 'Risiko Inkontinensia Urin Urgensi', 'Fisiologis', 'Eliminasi'],
            ['D.0052', 'Risiko Konstipasi Imajinasi', 'Fisiologis', 'Eliminasi'],
            ['D.0053', 'Disorganisasi Perilaku Bayi', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0054', 'Gangguan Mobilitas Fisik', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0055', 'Gangguan Pola Tidur', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0056', 'Intoleransi Aktivitas', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0057', 'Keletihan', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0058', 'Kesiapan Peningkatan Tidur', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0059', 'Risiko Disorganisasi Perilaku Bayi', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0060', 'Risiko Intoleransi Aktivitas', 'Fisiologis', 'Aktivitas & Istirahat'],
            ['D.0061', 'Disrefleksia Otonom', 'Fisiologis', 'Neurosensori'],
            ['D.0062', 'Gangguan Memori', 'Fisiologis', 'Neurosensori'],
            ['D.0063', 'Gangguan Menelan', 'Fisiologis', 'Neurosensori'],
            ['D.0064', 'Konfusi Akut', 'Fisiologis', 'Neurosensori'],
            ['D.0065', 'Konfusi Kronis', 'Fisiologis', 'Neurosensori'],
            ['D.0066', 'Penurunan Kapasitas Adaptif Intrakranial', 'Fisiologis', 'Neurosensori'],
            ['D.0067', 'Risiko Konfusi Akut', 'Fisiologis', 'Neurosensori'],
            ['D.0068', 'Risiko Disrefleksia Otonom', 'Fisiologis', 'Neurosensori'],
            ['D.0069', 'Disfungsi Seksual', 'Fisiologis', 'Reproduksi & Seksualitas'],
            ['D.0070', 'Pola Seksual Tidak Efektif', 'Fisiologis', 'Reproduksi & Seksualitas'],
            ['D.0071', 'Risiko Disfungsi Seksual', 'Fisiologis', 'Reproduksi & Seksualitas'],
            ['D.0072', 'Risiko Kehamilan Tidak Dikehendaki', 'Fisiologis', 'Reproduksi & Seksualitas'],
            ['D.0073', 'Kesiapan Persalinan', 'Fisiologis', 'Reproduksi & Seksualitas'],
            ['D.0074', 'Gangguan Rasa Nyaman', 'Psikologis', 'Nyeri & Kenyamanan'],
            ['D.0075', 'Ketidaknyamanan Pasca Partum', 'Psikologis', 'Nyeri & Kenyamanan'],
            ['D.0076', 'Nausea (Mual)', 'Psikologis', 'Nyeri & Kenyamanan'],
            ['D.0077', 'Nyeri Akut', 'Psikologis', 'Nyeri & Kenyamanan'],
            ['D.0078', 'Nyeri Kronis', 'Psikologis', 'Nyeri & Kenyamanan'],
            ['D.0079', 'Nyeri Melahirkan', 'Psikologis', 'Nyeri & Kenyamanan'],
            ['D.0080', 'Ansietas', 'Psikologis', 'Integritas Ego'],
            ['D.0081', 'Berduka', 'Psikologis', 'Integritas Ego'],
            ['D.0082', 'Distres Spiritual', 'Psikologis', 'Integritas Ego'],
            ['D.0083', 'Gangguan Citra Tubuh', 'Psikologis', 'Integritas Ego'],
            ['D.0084', 'Gangguan Identitas Diri', 'Psikologis', 'Integritas Ego'],
            ['D.0085', 'Gangguan Persepsi Sensori', 'Psikologis', 'Integritas Ego'],
            ['D.0086', 'Harga Diri Rendah Situasional', 'Psikologis', 'Integritas Ego'],
            ['D.0087', 'Harga Diri Rendah Kronis', 'Psikologis', 'Integritas Ego'],
            ['D.0088', 'Keputusasaan', 'Psikologis', 'Integritas Ego'],
            ['D.0089', 'Kesiapan Peningkatan Konsep Diri', 'Psikologis', 'Integritas Ego'],
            ['D.0090', 'Kesiapan Peningkatan Koping Keluarga', 'Psikologis', 'Integritas Ego'],
            ['D.0091', 'Kesiapan Peningkatan Koping Komunitas', 'Psikologis', 'Integritas Ego'],
            ['D.0092', 'Ketidakberdayaan', 'Psikologis', 'Integritas Ego'],
            ['D.0093', 'Ketidakpatuhan', 'Psikologis', 'Integritas Ego'],
            ['D.0094', 'Koping Keluarga Tidak Efektif', 'Psikologis', 'Integritas Ego'],
            ['D.0095', 'Koping Komunitas Tidak Efektif', 'Psikologis', 'Integritas Ego'],
            ['D.0096', 'Koping Tidak Efektif', 'Psikologis', 'Integritas Ego'],
            ['D.0097', 'Penurunan Koping Keluarga', 'Psikologis', 'Integritas Ego'],
            ['D.0098', 'Penyangkalan Tidak Efektif', 'Psikologis', 'Integritas Ego'],
            ['D.0099', 'Perilaku Kesehatan Cenderung Berisiko', 'Psikologis', 'Integritas Ego'],
            ['D.0100', 'Risiko Distres Spiritual', 'Psikologis', 'Integritas Ego'],
            ['D.0101', 'Risiko Harga Diri Rendah Kronis', 'Psikologis', 'Integritas Ego'],
            ['D.0102', 'Risiko Harga Diri Rendah Situasional', 'Psikologis', 'Integritas Ego'],
            ['D.0103', 'Risiko Ketidakberdayaan', 'Psikologis', 'Integritas Ego'],
            ['D.0104', 'Sindrom Post Trauma', 'Psikologis', 'Integritas Ego'],
            ['D.0105', 'Waham', 'Psikologis', 'Integritas Ego'],
            ['D.0106', 'Gangguan Komunikasi Verbal', 'Psikologis', 'Pertumbuhan & Perkembangan'],
            ['D.0107', 'Gangguan Tumbuh Kembang', 'Psikologis', 'Pertumbuhan & Perkembangan'],
            ['D.0108', 'Risiko Gangguan Perkembangan', 'Psikologis', 'Pertumbuhan & Perkembangan'],
            ['D.0109', 'Risiko Gangguan Pertumbuhan', 'Psikologis', 'Pertumbuhan & Perkembangan'],
            ['D.0110', 'Defisit Pengetahuan', 'Perilaku', 'Penyuluhan & Pembelajaran'],
            ['D.0111', 'Defisit Perawatan Diri', 'Perilaku', 'Kebersihan Diri'],
            ['D.0112', 'Kesiapan Peningkatan Pengetahuan', 'Perilaku', 'Penyuluhan & Pembelajaran'],
            ['D.0113', 'Pemeliharaan Kesehatan Tidak Efektif', 'Perilaku', 'Penyuluhan & Pembelajaran'],
            ['D.0114', 'Manajemen Kesehatan Keluarga Tidak Efektif', 'Perilaku', 'Penyuluhan & Pembelajaran'],
            ['D.0115', 'Manajemen Kesehatan Tidak Efektif', 'Perilaku', 'Penyuluhan & Pembelajaran'],
            ['D.0116', 'Risiko Proses Pengasuhan Tidak Efektif', 'Relasional', 'Interaksi Sosial'],
            ['D.0117', 'Gangguan Interaksi Sosial', 'Relasional', 'Interaksi Sosial'],
            ['D.0118', 'Gangguan Proses Keluarga', 'Relasional', 'Interaksi Sosial'],
            ['D.0119', 'Kesepian', 'Relasional', 'Interaksi Sosial'],
            ['D.0120', 'Isolasi Sosial', 'Relasional', 'Interaksi Sosial'],
            ['D.0121', 'Penampilan Peran Tidak Efektif', 'Relasional', 'Interaksi Sosial'],
            ['D.0122', 'Risiko Gangguan Perlekatan', 'Relasional', 'Interaksi Sosial'],
            ['D.0123', 'Risiko Isolasi Sosial', 'Relasional', 'Interaksi Sosial'],
            ['D.0124', 'Defisit Kesehatan Komunitas', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0125', 'Perlambatan Pemulihan Pascabedah', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0126', 'Risiko Cedera', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0127', 'Risiko Cedera Pada Ibu', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0128', 'Risiko Cedera Pada Janin', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0129', 'Gangguan Integritas Kulit/Jaringan', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0130', 'Hipertermia', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0131', 'Hipotermia', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0132', 'Perilaku Kekerasan', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0133', 'Perlambatan Pemulihan Pascabedah', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0134', 'Risiko Alergi', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0135', 'Risiko Bunuh Diri', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0136', 'Risiko Cedera', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0137', 'Risiko Cedera Pada Ibu', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0138', 'Risiko Cedera Pada Janin', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0139', 'Risiko Gangguan Integritas Kulit/Jaringan', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0140', 'Risiko Hipotermia', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0141', 'Risiko Hipotermia Perioperatif', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0142', 'Risiko Infeksi', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0143', 'Risiko Jatuh', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0144', 'Risiko Luka Tekan', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0145', 'Risiko Mutilasi Diri', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0146', 'Risiko Perdarahan', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0147', 'Risiko Perilaku Kekerasan', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0148', 'Risiko Termoregulasi Tidak Efektif', 'Lingkungan', 'Keamanan & Proteksi'],
            ['D.0149', 'Termoregulasi Tidak Efektif', 'Lingkungan', 'Keamanan & Proteksi'],
        ];

        foreach ($data as [$kode, $label, $kategori, $subkategori]) {
            DiagnosaSdki::withTrashed()->updateOrCreate(
                ['kode_diagnosa' => $kode],
                ['label_diagnosa' => $label, 'kategori' => $kategori, 'subkategori' => $subkategori, 'deleted_at' => null]
            );
        }
    }

    private function seedSlki(): void
    {
        // [kode, label] — 110 luaran SLKI
        $data = [
            ['L.03016', 'Adaptasi Neonatus'],
            ['L.12104', 'Adhesi Konseling'],
            ['L.13110', 'Ambuasi'],
            ['L.09067', 'Berat Badan'],
            ['L.01001', 'Bersihan Jalan Napas'],
            ['L.14125', 'Citra Tubuh'],
            ['L.12105', 'Dukungan Keluarga'],
            ['L.12106', 'Dukungan Sosial'],
            ['L.10098', 'Eliminasi Fekal'],
            ['L.04033', 'Eliminasi Urin'],
            ['L.07054', 'Fungsi Gastrointestinal'],
            ['L.02007', 'Fungsi Pankreas'],
            ['L.07055', 'Fungsi Seksual'],
            ['L.14126', 'Harga Diri'],
            ['L.14127', 'Harapan'],
            ['L.14128', 'Identitas Diri'],
            ['L.14129', 'Integritas Kulit dan Jaringan'],
            ['L.12107', 'Interaksi Sosial'],
            ['L.09068', 'Kapasitas Adaptif Intrakranial'],
            ['L.12108', 'Keamanan Lingkungan Rumah'],
            ['L.05039', 'Keberadaan Spiritual'],
            ['L.09069', 'Kesadaran'],
            ['L.05040', 'Keseimbangan Cairan'],
            ['L.05041', 'Keseimbangan Elektrolit'],
            ['L.03017', 'Keseimbangan Asam-Basa'],
            ['L.12109', 'Kesiapan Persalinan'],
            ['L.05042', 'Ketahanan Keluarga'],
            ['L.09070', 'Kontrol Emosi'],
            ['L.14130', 'Kontrol Gejala'],
            ['L.12110', 'Kontrol Infeksi'],
            ['L.14131', 'Kontrol Pengeluaran Feses'],
            ['L.14132', 'Kontrol Risiko'],
            ['L.09071', 'Memori'],
            ['L.12111', 'Motivasi'],
            ['L.01002', 'Mobilitas Fisik'],
            ['L.08063', 'Nausea (Mual)'],
            ['L.08064', 'Nilai-Nilai Spiritual'],
            ['L.08065', 'Nutrisi Bayi'],
            ['L.09092', 'Orientasi Kognitif'],
            ['L.05043', 'Pemulihan Pascabedah'],
            ['L.12112', 'Penampilan Peran'],
            ['L.13111', 'Pencitraan Diri'],
            ['L.02008', 'Pengetahuan'],
            ['L.09093', 'Perawatan Diri'],
            ['L.12113', 'Performa Peran'],
            ['L.02009', 'Perfusi Gastrointestinal'],
            ['L.02010', 'Perfusi Miokard'],
            ['L.02011', 'Perfusi Perifer'],
            ['L.02012', 'Perfusi Renal'],
            ['L.02013', 'Perfusi Serebral'],
            ['L.12114', 'Perilaku Kesehatan'],
            ['L.13112', 'Perilaku Kekerasan'],
            ['L.13113', 'Perkembangan Bayi'],
            ['L.13114', 'Perkembangan Anak'],
            ['L.01003', 'Pertukaran Gas'],
            ['L.01004', 'Pola Napas'],
            ['L.07056', 'Pola Seksual'],
            ['L.05044', 'Pola Tidur'],
            ['L.13115', 'Proses Pengasuhan'],
            ['L.13116', 'Proses Keluarga'],
            ['L.14133', 'Rasa Nyaman'],
            ['L.14134', 'Resolusi Berduka'],
            ['L.14135', 'Respon Alergi Lokal'],
            ['L.14136', 'Respon Alergi Sistemik'],
            ['L.14137', 'Respon Ventilasi Mekanik'],
            ['L.04034', 'Retensi Urin'],
            ['L.14138', 'Sensori Persepsi'],
            ['L.02014', 'Sirkulasi Spontan'],
            ['L.03018', 'Status Antenatal'],
            ['L.03019', 'Status Cairan'],
            ['L.03020', 'Status Intrapartum'],
            ['L.03021', 'Status Janin'],
            ['L.03022', 'Status Kenyamanan'],
            ['L.03023', 'Status Kesehatan Komunitas'],
            ['L.03024', 'Status Kesehatan Keluarga'],
            ['L.03025', 'Status Koping Keluarga'],
            ['L.03026', 'Status Koping Komunitas'],
            ['L.03027', 'Status Lingkungan'],
            ['L.03028', 'Status Menelan'],
            ['L.03029', 'Status Menyusui'],
            ['L.03030', 'Status Nutrisi'],
            ['L.03031', 'Status Nutrisi Bayi'],
            ['L.03032', 'Status Pascapartum'],
            ['L.03033', 'Status Perkembangan'],
            ['L.03034', 'Status Pertumbuhan'],
            ['L.03035', 'Status Spiritual'],
            ['L.06048', 'Status Termoregulasi'],
            ['L.14139', 'Tingkat Agitasi'],
            ['L.14140', 'Tingkat Ansietas'],
            ['L.14141', 'Tingkat Berduka'],
            ['L.14142', 'Tingkat Cedera'],
            ['L.14143', 'Tingkat Delirium'],
            ['L.14144', 'Tingkat Demensia'],
            ['L.14145', 'Tingkat Depresi'],
            ['L.14146', 'Tingkat Distres Spiritual'],
            ['L.14147', 'Tingkat Fatigue (Keletihan)'],
            ['L.14148', 'Tingkat Infeksi'],
            ['L.14149', 'Tingkat Jatuh'],
            ['L.14150', 'Tingkat Keberdayaan'],
            ['L.14151', 'Tingkat Kepatuhan'],
            ['L.14152', 'Tingkat Keputusasaan'],
            ['L.14153', 'Tingkat Kesadaran'],
            ['L.14154', 'Tingkat Koping'],
            ['L.14155', 'Tingkat Koping Maladaptif'],
            ['L.14156', 'Tingkat Luka Tekan'],
            ['L.14157', 'Tingkat Mobilisasi'],
            ['L.14158', 'Tingkat Mual/Muntah'],
            ['L.08066', 'Tingkat Nyeri'],
            ['L.14159', 'Tingkat Perdarahan'],
            ['L.14160', 'Tingkat Pengetahuan'],
        ];

        foreach ($data as [$kode, $label]) {
            LuaranSlki::withTrashed()->updateOrCreate(
                ['kode_luaran' => $kode],
                ['label_luaran' => $label, 'deleted_at' => null]
            );
        }
    }

    private function seedSiki(): void
    {
        // [kode, label] — 73 intervensi SIKI
        $data = [
            ['I.01006', 'Latihan Batuk Efektif'],
            ['I.01011', 'Manajemen Jalan Napas'],
            ['I.01014', 'Pemantauan Respirasi'],
            ['I.01026', 'Terapi Oksigen'],
            ['I.02033', 'Manajemen Aritmia'],
            ['I.02034', 'Manajemen Autotransfusi'],
            ['I.02035', 'Manajemen Cairan'],
            ['I.02036', 'Manajemen Defibrilasi'],
            ['I.02037', 'Manajemen Elektrolit'],
            ['I.02038', 'Manajemen Hiperglikemia'],
            ['I.02039', 'Manajemen Hipoglikemia'],
            ['I.02040', 'Manajemen Hipokalemia'],
            ['I.02041', 'Manajemen Hiponatremia'],
            ['I.02042', 'Manajemen Hipovolemia'],
            ['I.02043', 'Manajemen Imunisasi/Vaksinasi'],
            ['I.02044', 'Manajemen Nutrisi Parenteral'],
            ['I.02045', 'Manajemen Pacu Jantung Sementara'],
            ['I.02046', 'Manajemen Syok'],
            ['I.02047', 'Manajemen Syok Anafilaktik'],
            ['I.02048', 'Manajemen Syok Hipovolemik'],
            ['I.02049', 'Manajemen Syok Kardiogenik'],
            ['I.02050', 'Manajemen Syok Neurogenik'],
            ['I.02051', 'Manajemen Syok Septik'],
            ['I.02052', 'Pemantauan Cairan'],
            ['I.02053', 'Pemantauan Elektrolit'],
            ['I.02054', 'Pemantauan Hasil Laboratorium'],
            ['I.02055', 'Pemantauan Tanda Vital'],
            ['I.02075', 'Perawatan Jantung'],
            ['I.02076', 'Perawatan Jantung Akut'],
            ['I.02079', 'Perawatan Sirkulasi'],
            ['I.03091', 'Manajemen Nutrisi'],
            ['I.03112', 'Manajemen Eliminasi Urin'],
            ['I.03113', 'Manajemen Diare'],
            ['I.03114', 'Manajemen Konstipasi'],
            ['I.03119', 'Pemantauan Nutrisi'],
            ['I.03121', 'Pemantauan Cairan'],
            ['I.04148', 'Dukungan Ambulasi'],
            ['I.04149', 'Dukungan Mobilisasi'],
            ['I.05170', 'Dukungan Perawatan Diri'],
            ['I.05173', 'Dukungan Tidur'],
            ['I.06187', 'Manajemen Delirium'],
            ['I.06188', 'Manajemen Demensia'],
            ['I.06190', 'Manajemen Halusinasi'],
            ['I.06194', 'Manajemen Kejang'],
            ['I.06197', 'Pemantauan Tekanan Intrakranial'],
            ['I.06198', 'Perawatan Serebral'],
            ['I.07212', 'Manajemen Kesehatan Reproduksi'],
            ['I.07227', 'Perawatan Pascapersalinan'],
            ['I.08233', 'Pemberian Obat'],
            ['I.08234', 'Pemberian Obat Intravena'],
            ['I.08235', 'Pemberian Obat Oral'],
            ['I.08238', 'Manajemen Nyeri'],
            ['I.08242', 'Pemberian Analgetik'],
            ['I.08243', 'Pemberian Obat Inhalasi'],
            ['I.09265', 'Intervensi Krisis'],
            ['I.09274', 'Manajemen Kecemasan'],
            ['I.09312', 'Promosi Koping'],
            ['I.09314', 'Promosi Konsep Diri'],
            ['I.09321', 'Teknik Relaksasi'],
            ['I.09326', 'Terapi Aktivitas'],
            ['I.11348', 'Pencegahan Infeksi'],
            ['I.11353', 'Pencegahan Jatuh'],
            ['I.11357', 'Perawatan Luka'],
            ['I.12193', 'Edukasi Kesehatan'],
            ['I.12361', 'Edukasi Diet'],
            ['I.12362', 'Edukasi Latihan Fisik'],
            ['I.12383', 'Edukasi Manajemen Nyeri'],
            ['I.12395', 'Edukasi Pengobatan'],
            ['I.12463', 'Edukasi Teknik Napas'],
            ['I.14502', 'Manajemen Hipertermia'],
            ['I.14507', 'Manajemen Hipotermia'],
            ['I.14512', 'Manajemen Lingkungan'],
            ['I.14514', 'Manajemen Keselamatan Lingkungan'],
        ];

        foreach ($data as [$kode, $label]) {
            IntervensiSiki::withTrashed()->updateOrCreate(
                ['kode_intervensi' => $kode],
                ['label_intervensi' => $label, 'deleted_at' => null]
            );
        }
    }
}